version: '3.8'
services:
  gtmotive.estimate.microservice.host:
    ports:
      - "80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - MongoDb__ConnectionString=mongodb://mongodb:27017
      - MongoDb__MongoDbDatabaseName=VehicleRental
    depends_on:
      - mongodb
    networks:
      - app-network
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mongodb_data: